import { defaultHomePageSettings } from "./site-content"

export const defaultHomeBuilderSections = [
    {
        _key: "home-hero-current",
        _type: "heroSection",
        settings: {
            enabled: true,
            background: "white",
            contentWidth: "wide",
            spacingTop: "none",
            spacingBottom: "none",
            anchorId: "home",
        },
        layout: "current",
        height: "large",
        title: `${defaultHomePageSettings.heroTitleBefore} ${defaultHomePageSettings.heroTitleHighlight} ${defaultHomePageSettings.heroTitleAfter}`,
        overlayStrength: "none",
        primaryCta: {
            label: defaultHomePageSettings.heroPrimaryButtonLabel,
            linkType: "internal",
            internalRoute: defaultHomePageSettings.heroPrimaryButtonHref,
        },
        secondaryCta: {
            label: defaultHomePageSettings.heroSecondaryButtonLabel,
            linkType: "internal",
            internalRoute: defaultHomePageSettings.heroSecondaryButtonHref,
        },
    },
    {
        _key: "home-join-current",
        _type: "joinSection",
        settings: {
            enabled: true,
            background: "white",
            contentWidth: "wide",
            spacingTop: "medium",
            spacingBottom: "medium",
            anchorId: "join",
        },
        layout: "current",
        title: `${defaultHomePageSettings.recruitmentTitleBefore} ${defaultHomePageSettings.recruitmentTitleHighlight}`,
        showOpeningContent: true,
        primaryCta: {
            label: defaultHomePageSettings.contactButtonLabel,
            linkType: "email",
            email: defaultHomePageSettings.contactEmail,
        },
        secondaryCta: {
            label: defaultHomePageSettings.openingDetailsButtonLabel,
            linkType: "internal",
            internalRoute: defaultHomePageSettings.openingDetailsButtonHref,
        },
    },
    {
        _key: "home-research-current",
        _type: "researchSection",
        settings: {
            enabled: true,
            background: "light",
            contentWidth: "wide",
            spacingTop: "large",
            spacingBottom: "large",
            anchorId: "research",
        },
        title: "Research",
        description: "Edit the heading, layout preset, and number of research cards shown on the homepage.",
        layout: "cards",
        source: "latest",
        columns: 3,
        showCta: true,
        cta: {
            label: "View research",
            linkType: "internal",
            internalRoute: "/research",
        },
    },
    {
        _key: "home-publications-current",
        _type: "publicationSection",
        settings: {
            enabled: true,
            background: "white",
            contentWidth: "wide",
            spacingTop: "large",
            spacingBottom: "large",
            anchorId: "publications",
        },
        title: defaultHomePageSettings.selectedPublicationTitle,
        subtitle: defaultHomePageSettings.selectedPublicationSubtitle,
        source: "featured",
        limit: 6,
        layout: "current",
        columns: 3,
        showImage: true,
        showJournal: true,
        showYear: true,
        showAuthors: true,
        showPaperLink: true,
    },
    {
        _key: "home-news-current",
        _type: "newsSection",
        settings: {
            enabled: true,
            background: "light",
            contentWidth: "wide",
            spacingTop: "large",
            spacingBottom: "large",
            anchorId: "news",
        },
        title: defaultHomePageSettings.latestTitle,
        subtitle: "Latest updates from SPELL Lab.",
        source: "latest",
        limit: 3,
        layout: "cards",
        showViewAll: true,
        viewAllCta: {
            label: "View all news",
            linkType: "internal",
            internalRoute: "/news",
        },
    },
]

export const homeBuilderSetupGuide = [
    "1. Home Page Sections에 기본 섹션이 없으면 우측 상단 ... 메뉴에서 'Fill home builder defaults'를 누르세요.",
    "2. 각 섹션을 열어서 Title, Layout, Limit, CTA 같은 안전한 옵션만 수정하세요.",
    "3. 섹션 왼쪽 드래그 핸들로 순서를 바꾸고, Section Settings > Enabled로 숨기세요.",
    "4. 미리보기에서 확인하기 전까지 Enable Page Builder on Public Home은 꺼두세요.",
    "5. 문제 생기면 이 스위치를 다시 끄면 기존 홈페이지로 돌아갑니다.",
]
