import { defineField, defineType } from 'sanity'
import { defaultHomeBuilderSections, homeBuilderSetupGuide } from '../../lib/home-builder-defaults'
import { defaultHomePageSettings } from '../../lib/site-content'

export const homePageType = defineType({
    name: 'homePage',
    title: 'Home Page',
    type: 'document',
    groups: [
        { name: 'builder', title: 'Page Builder' },
        { name: 'hero', title: 'Hero' },
        { name: 'recruitment', title: 'Recruitment Section' },
        { name: 'publications', title: 'Selected Publications' },
        { name: 'latest', title: 'Latest Section' },
        { name: 'seo', title: 'SEO' },
    ],
    initialValue: {
        pageTitle: 'SPELL Home Page',
        ...defaultHomePageSettings,
        pageBuilderEnabled: false,
        builderSetupGuide: homeBuilderSetupGuide.join('\n'),
        sections: defaultHomeBuilderSections,
    },
    fields: [
        defineField({
            name: 'pageTitle',
            title: 'Page Name',
            type: 'string',
            group: 'builder',
            readOnly: true,
            description: 'Singleton document for the public homepage.',
            initialValue: 'SPELL Home Page',
        }),
        defineField({
            name: 'builderSetupGuide',
            title: 'How to Edit the Home Page',
            type: 'text',
            rows: 6,
            group: 'builder',
            readOnly: true,
            description: 'Quick guide. The public website does not switch to these sections until the enable switch below is turned on and published.',
            initialValue: homeBuilderSetupGuide.join('\n'),
        }),
        defineField({
            name: 'pageBuilderEnabled',
            title: 'Publish Page Builder on the Live Home Page',
            type: 'boolean',
            description: 'Keep this OFF while editing. OFF always shows the current legacy homepage. Turn ON only after preview/review.',
            group: 'builder',
            initialValue: false,
        }),
        defineField({
            name: 'sections',
            title: 'Sections - Add, Edit, Hide, Reorder',
            type: 'array',
            group: 'builder',
            description: 'Open a section to edit content and presets. Drag sections to reorder. Use Section Settings > Enabled to hide a section without deleting it.',
            initialValue: defaultHomeBuilderSections,
            of: [
                { type: 'heroSection' },
                { type: 'researchSection' },
                { type: 'joinSection' },
                { type: 'publicationSection' },
                { type: 'newsSection' },
                { type: 'gallerySection' },
                { type: 'memberSection' },
                { type: 'textSection' },
                { type: 'textImageSection' },
                { type: 'statsSection' },
                { type: 'ctaSection' },
            ],
        }),
        defineField({
            name: 'seoTitle',
            title: 'SEO Title',
            type: 'string',
            group: 'seo',
        }),
        defineField({
            name: 'seoDescription',
            title: 'SEO Description',
            type: 'text',
            rows: 3,
            group: 'seo',
        }),
        defineField({
            name: 'seoImage',
            title: 'Social Image',
            type: 'image',
            options: { hotspot: true },
            group: 'seo',
        }),
        defineField({
            name: 'heroTitleBefore',
            title: 'Hero Title Before Highlight',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'heroTitleHighlight',
            title: 'Hero Title Highlight',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'heroTitleAfter',
            title: 'Hero Title After Highlight',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'heroPrimaryButtonLabel',
            title: 'Primary Button Label',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'heroPrimaryButtonHref',
            title: 'Primary Button Link',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'heroSecondaryButtonLabel',
            title: 'Secondary Button Label',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'heroSecondaryButtonHref',
            title: 'Secondary Button Link',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'scrollLabel',
            title: 'Scroll Indicator Label',
            type: 'string',
            group: 'hero',
        }),
        defineField({
            name: 'recruitmentTitleBefore',
            title: 'Recruitment Title Before Highlight',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'recruitmentTitleHighlight',
            title: 'Recruitment Title Highlight',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'researchAreasHeading',
            title: 'Research Areas Heading',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'openingPositionsHeading',
            title: 'Opening Positions Heading',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'eligibilityHeading',
            title: 'Eligibility Heading',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'howToApplyHeading',
            title: 'How to Apply Heading',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'contactButtonLabel',
            title: 'Contact Button Label',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'contactEmail',
            title: 'Contact Button Email',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'openingDetailsButtonLabel',
            title: 'Opening Details Button Label',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'openingDetailsButtonHref',
            title: 'Opening Details Button Link',
            type: 'string',
            group: 'recruitment',
        }),
        defineField({
            name: 'selectedPublicationTitle',
            title: 'Selected Publication Section Title',
            type: 'string',
            group: 'publications',
        }),
        defineField({
            name: 'selectedPublicationSubtitle',
            title: 'Selected Publication Section Subtitle',
            type: 'string',
            group: 'publications',
        }),
        defineField({
            name: 'viewPaperLabel',
            title: 'View Paper Button Label',
            type: 'string',
            group: 'publications',
        }),
        defineField({
            name: 'noPublicationImageLabel',
            title: 'No Publication Image Label',
            type: 'string',
            group: 'publications',
        }),
        defineField({
            name: 'carouselPreviousLabel',
            title: 'Previous Publication Button Label',
            type: 'string',
            group: 'publications',
        }),
        defineField({
            name: 'carouselNextLabel',
            title: 'Next Publication Button Label',
            type: 'string',
            group: 'publications',
        }),
        defineField({
            name: 'latestTitle',
            title: 'Latest Section Title',
            type: 'string',
            group: 'latest',
        }),
        defineField({
            name: 'latestPlaceholder',
            title: 'Latest Section Placeholder Text',
            type: 'string',
            group: 'latest',
        }),
    ],
    preview: {
        select: {
            title: 'pageTitle',
            enabled: 'pageBuilderEnabled',
            sections: 'sections',
        },
        prepare({ title, enabled, sections }: { title?: string; enabled?: boolean; sections?: unknown[] }) {
            return {
                title: title || 'SPELL Home Page',
                subtitle: `${enabled ? 'Page Builder live' : 'Legacy homepage live'} - ${sections?.length || 0} builder sections`,
            }
        },
    },
})
